#!/usr/bin/env bash
sudo iapt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
sudo service nginx restart
echo "Nginx installed and configured successfully."
