#!/usr/bin/env bash
# installing nginx to server

sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
sudo bash -c "echo 'Hello Wprl!' > /
var/www/html/index.html"
# starting nginx service
sudo service nginx start
