#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi
cp /etc/hosts ~/hosts.new
echo "127.0.0.2         localhost" > ~/hosts.new
echo "8.8.8.8           facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
